### ISSUE TITLE
ModuleNotFoundError: No module named 'TransportNSWv2'

### ISSUE THREAD

**Issue by adampetrovic** [andystewart999/ha_transportnsw#7]
I'm trying out this integration and am getting the following error on HomeAssistant startup:

```
2024-10-23 17:20:02.861 ERROR (MainThread) [homeassistant.config] Platform error: sensor - No module named 'TransportNSWv2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config.py", line 1413, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1100, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1195, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'TransportNSWv2'
2024-10-23 17:20:02.863 ERROR (MainThread) [homeassistant.config] Platform error: sensor - No module named 'TransportNSWv2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config.py", line 1413, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1100, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1195, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'TransportNSWv2'
```

I don't have the 'official' `transport_nsw` integration configured with any sensors. How do you suggest I proceed in getting this integration to work?

**Comment by andystewart999** [comment]
That's strange.  You don't need the ```transport_nsw``` integration set up at all, mine is entirely separate.  I did have an earlier issue with duplicate module names but that's been fixed for a while now.

Can you tell me how you've installed the integration, what version you're running and paste in your config?  Feel free to redact the actual origin and destination IDs if you prefer.

**Comment by andystewart999** [comment]
I'm going to go ahead and close this issue, let me know if you're still having problems.
